name: CI

on:
  push:
    branches:
      - symon-storozhenko-ci-test
  pull_request:

env:
  PLAYWRIGHT_BROWSERS_PATH: 0

jobs:
  infra:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          python -m playwright install-deps
          python -m playwright install

  test:
    name: Test
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9, 3.10.4]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install -e .
          python -m playwright install-deps
          python -m playwright install
      - name: Test with Pytest
        run: pytest
